-- Application schema reference.
-- Laravel's default users migration must run before these tables are created.

CREATE TABLE templates (
    slug VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

INSERT INTO templates (slug, name, description, created_at, updated_at) VALUES
    ('minimal', 'Minimal', 'A clean, simple design that puts your profile and work first.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('creative', 'Creative', 'A colorful canvas for creativity, projects, and personality.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('professional', 'Professional', 'A polished layout for experience, achievements, and career.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    template_slug VARCHAR(255) NOT NULL DEFAULT 'minimal',
    headline VARCHAR(160),
    bio TEXT,
    location VARCHAR(120),
    avatar_url TEXT,
    website_url TEXT,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE TABLE portfolio_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    project_url TEXT,
    cover_image_url TEXT,
    position SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE INDEX portfolio_projects_profile_position_index
    ON portfolio_projects (profile_id, position);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    name VARCHAR(80) NOT NULL,
    position SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE
);

CREATE INDEX skills_profile_position_index ON skills (profile_id, position);
